export { default as UserHome } from "./User/UserHome/UserHome";
export { default as StaffHome} from "./Staff/StaffHome/StaffHome";
export { default as StaffDashBoard } from "./Staff/StaffDashBoard/StaffDashBoard";
export { default as StaffInventory} from "./Staff/StaffInventory/StaffInventory";
export { default as StaffReport} from "./Staff/StaffReport/StaffReport";
export { default as StaffDailyMenu} from "./Staff/StaffDailyMenu/StaffDailyMenu";
export { default as StaffPreorders} from "./Staff/StaffPreorders/StaffPreorders";
export { default as StaffSetting} from "./Staff/StaffSetting/StaffSetting";
export { default as AdminDashBoard} from "./Admin/AdminDashBoard/AdminDashBoard";
export { default as AdminManagement} from "./Admin/AdminManagement/AdminManagement";